export const CSHARP_START_CONNECTION = "CSHARP_START_CONNECTION";
export const CSHARP_STOP_CONNECTION = "CSHARP_STOP_CONNECTION";
export const CSHARP_PUBLISH_MESSAGE = "CSHARP_PUBLISH_MESSAGE";
export const CSHARP_NOTIFY_USER_CONNECTED = "CSHARP_NOTIFY_USER_CONNECTED";
export const CSHARP_NOTIFY_USER_DIS_CONNECTED = "CSHARP_NOTIFY_USER_DIS_CONNECTED";
export const CSHARP_NOTIFY_USER_DUPLICATED =  "CSHARP_NOTIFY_USER_DUPLICATED";
export const CSHARP_MESSAGE_RECEIVED = "CSHARP_MESSAGE_RECEIVED";

export const CHAT_MESSAGE = "CHAT_MESSAGE";